<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByCategory($category = '')
    {
        $query = $this->createQueryBuilder('product')
            ->where('product.category = :category')
            ->setParameter('category', $category->getId())
            ->getQuery();

        return $query->getResult();
    }
}
